// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReCrut.Infrastructure.SqlServer.ProjectionDatabase;

#nullable disable

namespace ReCrut.Infrastructure.SqlServer.ProjectionDatabase.Migrations
{
    [DbContext(typeof(ProjectionDbContext))]
    partial class ProjectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReCrut.Infrastructure.SqlServer.ProjectionDatabase.EfEntities.CandidatEfEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueIdentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CandidatStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("CandidatStatus");

                    b.Property<DateTime>("DatePriseContact")
                        .HasColumnType("datetime")
                        .HasColumnName("DatePriseContact");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Prenom");

                    b.Property<string>("Trigramme")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Trigramme");

                    b.HasKey("Id");

                    b.ToTable("Candidats", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
